services:
  web:
    tty: true
    stdin_open: true
    build: . 
    entrypoint: ./bin/docker-entrypoint
    command: sh -c "bin/rails s -p ${DOCKER_WEB_PORT:-3400} -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/time-tracker/usr/local/bundle
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${DOCKER_WEB_PORT:-3400}:3400"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://time-tracker:time-tracker@db:5432/time-tracker
      - ENABLE_BOOTSNAP=false

  db:
    image: postgres:16.3
    environment:
      POSTGRES_DB: time-tracker
      POSTGRES_PASSWORD: time-tracker
      POSTGRES_USER: time-tracker
    ports:
      - "${DOCKER_DB_PORT:-5432}:5432"
    expose:
      - "${DOCKER_DB_PORT:-5432}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U time-tracker -d time-tracker"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/time-tracker/var/lib/postgresql/data

volumes:
  bundle:
  pg_data:
